no_no_list = [
    " "
    ,""
    ,"\n"
    ,"\n    +\n"
    ,"\n    2\n"
    ,"\n  \n\n\n  \n\n\n"
    ,"\n\n      \n\n      \n"
    ,"\n\n"
    ,"\n\n\n"
    ,"\n\n\n\n"
    ,"\u3000"
    ,"\u3000\u3000"
    ,"ADVERTISEMENT"
    ,"comment-marker hide-marker on-inline-comments-modal"
    ,"Copyright © 2018-2022 Fuyu Neko's Translations. All rights reserved."
    ,"fa fa-comment-count fa-wp-neutral-2"
    ,"Facebook"
    ,"Glossary |"
    ,"Glossary"
    ,"If you enjoy my work, please consider sending this sleep deprived mtl-er some ko-fi. =)"
    ,"Index"
    ,"Leave a review in"
    ,"Leave a review in\xa0"
    ,"Like"
    ,"Next |"
    ,"Next"
    ,"None"
    ,"num-comment"
    ,"Please support me on ko-fi if possible:"
    ,"Prev"
    ,"Previous •"
    ,"Previous |"
    ,"Previous"
    ,"Privacy Policy"
    ,"Table of Contents |"
    ,"Table of Contents"
    ,"text-align: center"
    ,"TOC"
    ,"Twitter"
    ,None
]

img_suffixes = [
    ".gif"
    ,".img"
    ,".jpg"
    ,".png"
    ,".svg"
    ,"jpeg"
]