no_no_list = [
    " "
    ,""
    ,"\n"
    ,"\n    +\n"
    ,"\n    2\n"
    ,"\n  \n\n\n  \n\n\n"
    ,"\n\n      \n\n      \n"
    ,"\n\n"
    ,"\n\n\n"
    ,"\n\n\n\n"
    ,"\xa0"
    ,"\u3000"
    ,"\u3000\u3000"
    ,"ADVERTISEMENT"
    ,"'| Please consider pausing your Ad-blocker! Ads help to maintain this website. They are not intrusive, and you don’t need to click them! Thank you! |'"
    ,"***  | Please consider pausing your Ad-blocker! Ads help to maintain this website. They are not intrusive, and you don’t need to click them! Thank you! |"
    ,"comment-marker hide-marker on-inline-comments-modal"
    ,"Copyright © 2018-2022 Fuyu Neko's Translations. All rights reserved."
    ,"fa fa-comment-count fa-wp-neutral-2"
    ,"Facebook"
    ,"Glossary |"
    ,"Glossary"
    ,"If you enjoy my work, please consider sending this sleep deprived mtl-er some ko-fi. =)"
    ,"Index"
    ,"Leave a review in"
    ,"Leave a review in\xa0"
    ,"Like"
    ,"Next |"
    ,"Next"
    ,"None"
    ,"num-comment"
    ,"Please support me on ko-fi if possible:"
    ,"Prev"
    ,"Previous •"
    ,"Previous |"
    ,"Previous"
    ,"Privacy Policy"
    ,"Table of Contents |"
    ,"Table of Contents"
    ,"text-align: center"
    ,"TOC"
    ,"Twitter"
    ,None
    ,'Chrysanthemum Garden.'
    ,'Please visit chrysanthemumgarden (dot) com'
    ,"Chrysanthemum Garden."
    ,"Please visit chrysanthemumgarden (dot) com"
    ,"Please support our translators at chrysanthemumgarden (dot) com"
    ,"Read more BL at chrysanthemumgarden (dot) com"
    ,"Story translated by Chrysanthemum Garden."
    ]

img_suffixes = [
    ".gif"
    ,".img"
    ,".jpg"
    ,".png"
    ,".svg"
    ,"jpeg"
]