no_no_list = [
        "\n"
        ,"\n\n"
        ,"\n\n\n"
        ,"\n\n\n\n"
        ,"\n    +\n"
        ,"\n    2\n"
        ,"\n  \n\n\n  \n\n\n"
        ,"\n\n      \n\n      \n"
        ,"comment-marker hide-marker on-inline-comments-modal"
        ,"fa fa-comment-count fa-wp-neutral-2"
        ,"num-comment"
        ,"If you enjoy my work, please consider sending this sleep deprived mtl-er some ko-fi. =)"
        ,"Leave a review in"
        ,"Leave a review in\xa0"
        ,"Index"
        ,"TOC"
        ,"Twitter"
        ,"Facebook"
        ,"Like"
        ,"Glossary"
        ,"Table of Contents"
        ,"Next"
        ,"Next |"
        ,"Previous |"
        ,"Table of Contents |"
        ,"Glossary |"
        ,"ADVERTISEMENT"
        ,"Copyright © 2018-2022 Fuyu Neko's Translations. All rights reserved."
        ,"Privacy Policy"
        ,"\u3000\u3000"
        ,"\u3000"
        ,"Please support me on ko-fi if possible:"
        ,"Previous •"
        ,"Previous"
        ,"Prev"
        ," "
        ,""
        ,"text-align: center"
        ,None
        ,"None"
    ]